### ISSUE TITLE
circle_trigger.shのライセンスについて

### ISSUE THREAD

**Issue by polyomino24** [taiga248/monorepo#22]
zennの記事を読ませていただきました。
こちらのコードは[こちらのリポジトリ](https://github.com/labs42io/circleci-monorepo)からコピペしてきたものであり、ライセンス違反ではないでしょうか？元のリポジトリは少なくとも3年前からMITライセンスが適用されています。
https://github.com/taiga248/monorepo/blob/f441a411af48961a10c18c1db5ea249a08b0ff26/.circleci/circle_trigger.sh

**Comment by taiga248** [comment]
@polyomino-24 
ご指摘ありがとうございます。Licenseファイルを置かせていただきました。
MITライセンスへの理解が浅く、参照元へのリンクを貼れば問題ないと思い込んでいました。
今後このようなことがないよう努めます。すみませんでした。
また、過ちに気付かせていただきありがとうございました。
